### ISSUE TITLE
Build fails on Ubuntu withou these extra dependancies

### ISSUE THREAD

**Issue by wintercooled** [Blockstream/green_cli#6]
Perhaps they could be mentioned in the README?

`sudo apt-get install libudev-dev libusb-1.0-0-dev libfox-1.6-dev`

References: 

https://pypi.org/project/trezor/

https://8vi.cat/solution-to-trezor-agent-installation-problems-on-ubuntu/

**Comment by grubles** [comment]
What Ubuntu version are you running?

**Comment by wintercooled** [comment]
19.10 with 'minimal' install option.

**Comment by jgriffiths** [comment]
I needed libudev-dev and libusb-1.0-0-dev on a development debian buster box (that builds everything else in the the GA stable of software), +1 for listing these in README.md IMO.

**Comment by jgriffiths** [comment]
Fixed by bb650f1f25f9973373f59d2b358364a8b98afea5, closing.
