### ISSUE TITLE
Example in readme uses setmnemonic which isn't a command

### ISSUE THREAD

**Issue by wintercooled** [Blockstream/green_cli#7]
Perhaps it used to be? setmnemonic is not listed in help or in code.
`
green-cli --network testnet setmnemonic /file/containing/testnet/mnemonics`

**Comment by jkauffman1** [comment]
Fixed by

https://github.com/Blockstream/green_cli/commit/28af55200c85b622408d93556ba3bde4b32e7bd5

thanks
